### ISSUE TITLE
Upgrade proposal - No action on students missing in the CSV

### ISSUE THREAD

**Issue by giuseppeperelli** [mauman/infostud-load-csv#3]
Add an option to keep the students non-recorded in case they do not appear in the CSV.
At the current state, every student missing from the CSV is recorded as "Absent". This might be error-prone.
How about adding a tickbox in the loop to allow a no-action for this case?

**Comment by asterbini** [comment]
All votes should be explicit, I think

**Comment by asterbini** [comment]
Done
