### ISSUE TITLE
Error message for rejecting students

### ISSUE THREAD

**Issue by giuseppeperelli** [mauman/infostud-load-csv#4]
The latest version of the script is getting an error message for rejecting students. The value "R" is not accepted on INFOSTUD as it is not a number. It works well by commenting out line 103 of the code.
I do not have the right to make pull requests, so I am opening an issue on this.

**Comment by asterbini** [comment]
Thanks!Andrea On 12 Apr 2024 5:11 pm, Giuseppe Perelli ***@***.***> wrote:
The latest version of the script is getting an error message for rejecting students. The value "R" is not accepted on INFOSTUD as it is not a number. It works well by commenting out line 103 of the code.
I do not have the right to make pull requests, so I am opening an issue on this.

**Comment by asterbini** [comment]
Fixed
